### PR TITLE
Min values for number ranges

### PR DESCRIPTION
**Pull request by Niels-Erik**
Added the possibility for '-*' in ranges of type refinements, and did some refactoring and commenting of peculiarities.

### CODE REVIEW

**Comment by fmontesi** [comment]
@jolie/core Can I get a double check on using `-*` as syntax for 'minimum integer or double'? Please comment.

**Comment by fmontesi** [comment]
Basically you can now write things like `ranges( [-*,10] )` to express an
integer from MIN_INT (which is negative) to 10. We cannot currently express
MIN_INT in ranges.

What I'm asking is: is this a good syntax for expressing MIN_INT?

**Comment by klag** [comment]
But the idea is that, when there is '-*' there is no lower limit, right?

**Comment by fmontesi** [comment]
Right (well, no limit on top of what the type supports, like int can't go
lower than MIN_INT)

**Pull request merged**
