### PR TITLE
Cleaning choice operator on java8

### PR DESCRIPTION
**Pull request by agwe**

### CODE REVIEW

**Comment by fmontesi** [comment]
This is now merged!

I've added a restructuring of the Type classes to show where our code breaks due to not being able to handle choice types yet. Before, this was hidden by your empty implementation methods, @agwe, or sometimes you were just returning the native type or subtypes of one of the two types in the choice (whereas we should correctly reason about both when dealing with choice types in our tools).

Thanks a lot for your hard work @agwe ! Please remember to add your Name and e-mail to the copyright header of TypeChoiceDefinition.java

Now, we should fix the tools. Can you help? I suggest starting from joliedoc and do a pull request just for that, and continue like that for each tool, so that we can discuss just the patch on joliedoc to understand what to do and then go forward.

**Comment by agwe** [comment]
Hello Fabrizio,

I'm very happy, that you have accepted the code and eager to work further
on fixing tools and any other tasks on the interpreter. I'm going to start
looking on it tomorrow, how do you think, are there any particular things I
should know to pay attention on them?
I also remember, that I still haven't made any tests for choice operator.

Best Regards,
Larisa



2015-09-11 9:59 GMT+03:00 Fabrizio Montesi <notifications@github.com>:

**Comment by fmontesi** [comment]
Hi Larisa,

Sounds good! Well, the problem now is basically that having a TypeDefinition does not guarantee that we have access to nativeType and subtypes, because in general that may not exist, in the case of a TypeChoice. So now we need to go by cases. If it's a type choice, we have to access left and right and do something with them (and this recursively, since left and right may themselves be TypeChoices). Otherwise, if it's a TypeDefinitionLink, we can recursively access the linkedType(). It all ends once we hit a TypeInlineDefinition, which can finally tell us what subTypes we have.

I was suggesting to start from joliedoc and then commenting on that since then we should probably follow the same methodology for all the rest.

I made a simple test in test/primitives/types for now, which includes choice types, so if you want to add something feel free to extend that.

Best,
Fabrizio

**Comment by fmontesi** [comment]
Hi @agwe , did you manage to start working on joliedoc? Let me know if you need any help!

- Fabrizio

**Comment by agwe** [comment]
Hello Fabrizio,

Sory, for long idle. I've fixed jolidoc and pushed to fork, but haven't
made pul request yet. Trying to get rid of unnecessary 6 commits and change
code style again. I will make pull request tomorrow with the cleaned
version. Could I ask you please, to look at my fork, if you have time, so
to be sure, that I'm doing things in the right way? Or better to make pull
request at first?

Best Regards,
Larisa

2015-09-24 10:47 GMT+03:00 Fabrizio Montesi <notifications@github.com>:

**Comment by fmontesi** [comment]
Hi Larisa,

Terrific! It looks generally fine, so feel free to go ahead and create a pull request!

/ Fabrizio

**Comment by agwe** [comment]
Hi,

Thank you for merging) May I proceed with other tools?

Best Regards,
Larisa

2015-09-25 10:08 GMT+03:00 Fabrizio Montesi <notifications@github.com>:

**Comment by fmontesi** [comment]
Yes, please do! :-) :+1:

Once we're finished and everything compiles again we should try out joliedoc on the website documentation. @thesave can you help us with that?

**Comment by thesave** [comment]
Definitely. Let me know when it is stable enough to try it on the docs.

**Pull request merged**
